services:
  backend:
    image: 580704946874.dkr.ecr.us-east-2.amazonaws.com/back
    build: backend
    ports:
      - 8000:8000
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:app

  frontend:
    image: 580704946874.dkr.ecr.us-east-2.amazonaws.com/front
    build: frontend
    ports:
      - 80:80
    depends_on:
      - backend

